<h1>Numpy</h1>
It's a python library for working with arrays.<br>
It also ships with functions for working in the domain of linear algebra, fourier transform and matrices.

Numpy's array object is called <strong><i>ndarray</i></strong> and it has numerous supporting functions. Numpy's array object is multiple times faster and efficient than python's built-in lists.

In [5]:
# testing numpy is installed in the current environment.
import numpy as np
print(np.__version__)

1.19.0


In [9]:
l = [1,2,3,4,5]
t = (1,2,3,4,5)
arr = np.array(l)
arr2 = np.array(t)

print(type(l))
print(type(t))
print(type(arr))
print(type(arr2))

print(l)
print(t)
print(arr)
print(arr2)

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5]
(1, 2, 3, 4, 5)
[1 2 3 4 5]
[1 2 3 4 5]


<h2>Dimensions in Arrays</h2>
A dimension in arrays is one level of array depth (nested arrays).<br>
<h3>0-D Arrays (Scalars)</h3>
Elements in an array. Each element is a 0-D array.
<h3>1-D Array /Uni-dimensional Array</h3>
An array that's made up of 0-D arays.
<h3>2-D Arrays</h3>
An arrays that's has 1-D arrays as it's elements. They often represent matrix or 2nd order tensors.
<h3>3-D Arrays</h3>
An array that has 2-D arrays as its elements.
<h3>Checking the number of Dimensions</h3>
<strong><i>ndim</i></strong> is the array attribute that returns a integer that tells how many dimensions the array has.

In [17]:
a = np.array(42)
print(a)
print("Dimensions:", a.ndim)
b = np.array([1, 2, 3, 4,5])
print(b)
print("Dimensions:", b.ndim)
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print("Dimensions:", c.ndim)
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])
print(d)
print("Dimensions:", d.ndim)

42
Dimensions: 0
[1 2 3 4 5]
Dimensions: 1
[[1 2 3]
 [4 5 6]]
Dimensions: 2
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimensions: 3


<h3> Higher Dimensional Arrays</h3>
An array can have any number of dimensions.<br>
When an array is created, passing the <strong><i>ndmin</i></strong> argument can be used to specify the dimensions.

In [19]:
arr = np.array([1, 2, 3, 4, 5], ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


<h2>Numpy Array Indexing</h2>
You can access any element by referring to its index number. Indexing begins at 0.<br>
For multi-dimensional arrays, use comma separated integers representing the dimension and the index of the element.

In [26]:
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[2] + arr[3])

# multi-dimensional arrays.
# Access the 2nd element on the 1st dimension
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('3nd element on 1st dim: ', arr[0, 1])
# Access the 3 element on the 2nd dimension
print('3rd element of the 2nd dimension: ', arr[1, 2])

# 3 dimensional array
# Access the third element of the second array of the first array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

1
2
3
4
7
3nd element on 1st dim:  2
3rd element of the 2nd dimension:  8
6


<h3>Negative indexing</h3>
Use Negative indexing to access an array from the end.

In [28]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# print the last element from the second dimension.
print(arr[-1, -1])
print(arr[1, -1])

10
10


In [13]:
## Slicing Arrays
This involves taking elements from one given index to another given index.<br>
The is done by passing slice like this: <strong>[start:end]</strong><br>
We can define the step like this: <strong>[start:end:step]</strong><br>
If pass is not passed it is considered 0<br>
If end is not passed it is considered the length of the array in that dimension.<br>
If step is not passed it is considered 1
To slice from the end, use negative indexing.

[2 3 4]
[1 2 3 4]
[5 6 7]
[1 2 3 4 5 6 7]
[1 3 5 7]
[1 2 3 4 5]
[]
[3 4 5]


import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:4])
print(arr[:4])
print(arr[4:])
print(arr[:])
print(arr[::2])
print(arr[:-2])
#  In reverse indexing, the order of the indices should be reverse chronology
print(arr[-2:-5])
print(arr[-5:-2])

In [18]:
### Slicing 2-D Arrays

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# From the second element, slice elements from index 1 to index 4
print(arr[1, 1:4])

#  from both elements return index 2.
print(arr[0:2, 2])

# From both elements, slice index 1 to index 4 (not included)
print(arr[0:2, 1:4])

## Numpy Data Types

In [23]:
Python has the below data types:
* strings
* integer
* float
* boolean
* complex
Numpy has some extra datatypes and refers to data types with one character. Below is a list of numpy data types and the characters used to represent them.
* **i** - nteger
* **b** - boolean
* **u**- unsigned boolean
* **f** float
* **c**- complex float
* **m** - timedelta
* **M** - datetime
* **O** - object
* **S** - string
* **U** - unicode string
* **V** - fixed chunk of memory for other type ( void )
### Checking the Data Type of an Array
The numpy array object has a property called **dtype** that returns the data type of the array.

int64
<U5


import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr.dtype)

arr = np.array(['Mon', 'Tue', 'Wed', 'Thurs'])

print(arr.dtype)

In [29]:
#### Creating Arrays with a Defined Data Type
The array() function takes optional argument: dtype that allows us to defined the expected data types of array elements.<br>
For i, u, f, S and U we can define the size as well.<br>
**What if the passed argument doesn't represent a valid numpy data type?** Numpy will raise a Type error.<br>
**What is a value cannot be casted?** Numpy will raise a Value error

|S1
int32


import numpy as np

arr = np.array([1, 2, 3, 4, 5], dtype='S')

print(arr.dtype)

#  array with 4 bytes integers
arr = np.array([1, 2, 3, 4, 5], dtype='i4')

print(arr.dtype)

In [1]:
#### Converting Data Type of Existing Arrays
The best way to change the data type of an existing array is to make a copy of the array with the astype() method.

[1.1 2.2 3.3 4.4 5.5]
float64
[1 2 3 4 5]
int32
[False  True  True]
bool


import numpy as np

arr = np.array([1.1, 2.2, 3.3, 4.4, 5.5])

newarr = arr.astype('i')

print(arr)
print(arr.dtype)
print(newarr)
print(newarr.dtype)

arr = np.array([0, 1, 2])
arr2 = arr.astype(bool)
print(arr2)
print(arr2.dtype)

In [4]:
## Numpy Array Copy vs View
A copy and a view of an array differ from one another in that the copy is a new array while the view is just a view of the original array. The copy owns the data and any changes made to the copy do not affect the original array, and at the same time subsequent changes made to the original will not affect the copy. The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

[42  2  3  4  5]
[1 2 3 4 5]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

In [7]:
### Check if Array owns it's Data
Every Numpy array has the attribute base that returns None if the array owns the data. Otherwise, the base attribute refers to the original object.

None
[1 2 3 4 5]


import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

In [13]:
## Numpy Array Shape
### Shape of an Array
The share of an aray is the number of elements in each dimension.
### Get the Shape of an Array
Each Numpy array has an attribute called shape that returns a tuple with each index having the number of corresponding elements. Integers at every index of the tuple tells about the number of elements the corresponding dimension has.

Shape:  (2, 4)
Dimension of the same array: 2
[[[[[1 2 3 4]]]]]
shape of array:  (1, 1, 1, 1, 4)
Dimension of the same array:  5


import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("Shape: ", arr.shape)
print("Dimension of the same array:", arr.ndim)

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print("shape of array: ", arr.shape) 
print("Dimension of the same array: ", arr.ndim) 


In [2]:
## Reshaping Arrays
Reshaping entails changing the shape of an Array. By reshaping, we can add or remove dimensions or change number of elements in each dimension.
### Reshaping from 1-D to 2-D
Below code snippet

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Original array shape: (12,)
Original array dimension: 1
New array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
New array shape: (4, 3)
New array dimensions: 2


import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Original array:", arr)
print("Original array shape:", arr.shape)
print("Original array dimension:", arr.ndim)

newarr = arr.reshape(4, 3)

print("New array:\n", newarr)
print("New array shape:", newarr.shape)
print("New array dimensions:", newarr.ndim)


In [1]:
### Reshape From 1-D to 3-D

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new_array = arr.reshape(2, 3, 2)
print(new_array)
print(new_array.ndim)


In [5]:
## Can we Reshape into any Shape?
Short answer: Yes <br>
Long answer: It is required that the number of elements required for reshaping is equal to the number of elements in the original array.
## Is reshaping copying of viewing?
Reshaping is viewing.

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4))
print(arr.reshape(2, 4).base)


In [8]:
## Unknown Dimension
It is allowed to have one Unknown Dimension. You do not have to specify the exact number for one of the dimensions in the reshape method.<br>
By passing -1 as the value, NumPy will calculate this number for you. -1 cannot be passed to more than one dimension.

array [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dimensions: 3
shape: (2, 2, 2)


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print("array", newarr)
print("dimensions:", newarr.ndim)
print("shape:", newarr.shape)

array [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dimensions: 3
shape: (2, 2, 2)


## Flattening the arrays
Flattening means converting a multidimensional array into a 1D array. we can use **reshape(-1)** to do this.

In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr) 

[1 2 3 4 5 6]


## Numpy Iterating
### Iterating Arrays
Iterating means going through elements one by one. A for loop can be used to iterate arrays.<br>
Below is a example with a 1-D array.

In [3]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


### Iterating Multidimensional Arrays
Iterating an n-D array goes through n-1th dimension one by one.

In [10]:
import numpy as np
# 2-d Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

# 3-d Array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


## Iterating Arrays Using nditer()
The function nditer() is a helper function that can be used from a vast range of iterations.
### Iterating on each Scalar Element
Using nditer() we can loop through any n-D array to get each element. Were we using basic for loops, we would have to write n for loops - clumsy, right?.

In [12]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x) 

1
2
3
4
5
6
7
8


## Iterating Array with Different Data Types
We can use **op_dtypes** argument and pass it the expected datatype to change the datatype of elements while iterating. Since Numpy does not change the data tyoe of the element in-place, it needs some space to perform this action. This extra space is called buffer, and in order to enable it in nditer() we pass the **flags=\['buffered']**

In [13]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x) 

b'1'
b'2'
b'3'


## Iterating With Different Step Size
To iterating using steps different from 1, we can use filtering and iterating.

In [14]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x) 

1
3
5
7


## Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one. If we need the corresponding index og the element while iterating, the **ndenumerate**() method can be used.

In [18]:
import numpy as np

# 1-D array
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

#  2-D Array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x) 

(0,) 1
(1,) 2
(2,) 3
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
